### ISSUE TITLE
Website tags missing "http://" or "www."

### ISSUE THREAD

**Issue by NextlevelFernando** [pulilab/vue-people#102]
Hello there!

Upon submitting the form, after logging in through Github, if your website URL is formatted as "website.com", it'll not show the input as being invalid, but will not process your request for signup:

Payload: {"website_url":["Enter a valid URL."]}

Error: fails to load /api/user/:1, with a 400 error code.

Suggestion: make the input invalid if it's missing that info,

**Comment by lordfuoco** [comment]
@NextlevelFernando Thanks for the report!
