### ISSUE TITLE
Synergizing efforts with VueMeetups.org

### ISSUE THREAD

**Issue by bencodezen** [pulilab/vue-people#110]
Hello!

I'm one of the co-founders of VueMeetups.org. In an effort to reduce fragmentation within the community, I wanted to reach out because both groups seem to be trying to achieve similar goals as far as making it easy for people to find and meet other Vue.js developers.

It would be great to get your thoughts on this when you have some time. Thanks!

**Comment by lordfuoco** [comment]
@bencodezen Thank you for reaching out! I leave you in the hands of @torbent

**Comment by torbent** [comment]
Hi @bencodezen we are totally open to synchronising the the efforts where it make sense. I checked vuemeetups.org, and I see we maintain a lot of the same data. Should we take this conversation to email? t@pulilab.com
