### ISSUE TITLE
Enhannce twitter_url field

### ISSUE THREAD

**Issue by nomeacuerdo** [pulilab/vue-people#111]
**@username** is not valid.
**twitter.com/username** is valid on the app, but the endpoint returns an error 400 with payload `{"twitter_url":["Enter a valid URL."]}` and no visible response on the frontend
**http://www.twitter.com/username** is apparently the only valid format.

The field should either:
1. have a mask, placeholder explaining the intended format, or even better, both.
2. Match the field validity with that of the backend.

**Comment by lordfuoco** [comment]
@nomeacuerdo Thank you for reporting this! We will try to include it in the next update!
