### ISSUE TITLE
Tag list dropdown is broken

### ISSUE THREAD

**Issue by immarina** [pulilab/vue-people#126]
Hi! The v-select dropdown for the taglist on the profile form is broken.

It looks like the data coming from https://vuepeople.org/api/tags/ is actually giving two props, "name" and "slug" but v-select expects "label" and "value" in order for it to work.

So instead of the values its outputting [object object] :)

**Comment by lordfuoco** [comment]
@immarina Thank you for the issue, you are right! We released an update to the tag system today and.. ops forgot about the profile! Fixing it right no!

**Comment by lordfuoco** [comment]
@immarina Fixed and released! And sorry for the mistake :)
