### ISSUE TITLE
Your SSL Expired

### ISSUE THREAD

**Issue by joeelia** [pulilab/vue-people#128]
The LetsEncrypt Certificate for https://vuepeople.org/ expired on Sunday, February 24, 2019 at 4:09:30 AM Eastern Standard Time. Not really an 'issue' for the code, but just letting you know.

**Comment by DonNicoJs** [comment]
@joeelia Thank you very much! I am going to refresh it now

**Comment by DonNicoJs** [comment]
Refreshed! Thank you
