### ISSUE TITLE
Make email not mandatory, or clearly state that it will be shown 

### ISSUE THREAD

**Issue by lordfuoco** [pulilab/vue-people#13]
More than one person request the ability to mask the email from being publicly shown

**Comment by nullcode** [comment]
@lordfuoco Okay, let's add a checkbox for hiding your email address

**Comment by filipalacerda** [comment]
I bumped into this today. I didn't fill the email field and couldn't do anything, but there was no visible error. Had to use the dev tools to check that the error sent in the API response was "email is mandatory".

Maybe add a message with possible errors after submitting the profile?

**Comment by lordfuoco** [comment]
Hi @filipalacerda thank you for the comment! 
We noticed it as well we opened this issue: #41 you can follow there for updated on this
