### ISSUE TITLE
Certificate Expired

### ISSUE THREAD

**Issue by Alan-Liang** [pulilab/vue-people#132]
The cert of <https://vuepeople.org/> has expired on 2020/3/13, similar to #131.

**Comment by Chris2011** [comment]
Yeah, please update the cert or create an automatic process for that, to avoid the expiration again :) BTW the site is very cool @DonNicoJs @nullcode :)

**Comment by nmezzopera** [comment]
I am on it :) also we will have to fix the github API soon too :D

**Comment by Alan-Liang** [comment]
Expired on 2020/7/9 again :(

**Comment by nmezzopera** [comment]
@Alan-Liang Apologies :( refreshed!

**Comment by Chris2011** [comment]
I guess you use LetsEncrypt, right? So it would be good to have an automatism for that. Unfortunately I don't know your infrastructure to help here.

**Comment by nmezzopera** [comment]
@Chris2011 I need to setup a chron job to deal with it :)

**Comment by Chris2011** [comment]
Oki, sounds legit :)

**Comment by Chris2011** [comment]
It is still invalid, it gets a running gag :D. Just joking :). Maybe we can have a chat and talk about what needs to be done or how the infrastracture is. That I can help here if you want.

**Comment by nmezzopera** [comment]
@Chris2011 🤦  I finally gave in!

```
people@vue-people-1:~/vue-people$ sudo crontab -l
# Edit this file to introduce tasks to be run by cron.
#
# Each task to run has to be defined through a single line
# indicating with different fields when the task will be run
# and what command to run for the task
#
# To define the time you can provide concrete values for
# minute (m), hour (h), day of month (dom), month (mon),
# and day of week (dow) or use '*' in these fields (for 'any').#
# Notice that tasks will be started based on the cron's system
# daemon's notion of time and timezones.
#
# Output of the crontab jobs (including errors) is sent through
# email to the user the crontab file belongs to (unless redirected).
#
# For example, you can run a backup of all your user accounts
# at 5 a.m every week with:
# 0 5 * * 1 tar -zcf /var/backups/home.tgz /home/
#
# For more information see the manual pages of crontab(5) and cron(8)
#
# m h  dom mon dow   command

0 3 * * * /home/*^&^&*/vue-people/refresh-cert.sh
```
