### ISSUE TITLE
What is this and how did I end up on it?

### ISSUE THREAD

**Issue by rijkvanzanten** [pulilab/vue-people#133]
Hi there!

I just found my picture and name pinpointed on the map in this project, but I have no idea what it is or how I ended up on it. I wasn't notified of this nor did I even consent to have my information shared in this manner..

Maybe consider adding a "Hey, someone is trying to add you to vuepeople.org. Click here to accept the invite." flow or something along those lines.

Happy open-sourcing! 
~ Rijk

**Comment by nullcode** [comment]
Hi @rijkvanzanten,
we don't have an invitation based signup, you can only put yourself on the map. That means that either you or someone who was logged in w your github account put you on the map or someone has cloned your name and picture with a fake github account.

Cheers

**Comment by rijkvanzanten** [comment]
Weird.. Can't remember having ever seen this nor can I find it in authorized GitHub apps. Must've been a while ago I guess 🤷
