### ISSUE TITLE
Display fewer results in smaller zoom levels

### ISSUE THREAD

**Issue by SevenOutman** [pulilab/vue-people#16]
When registered locations gets much more, it can be really crowded and with poor performance if I'm seeing the full map with all results shown. 
A common solution is to display fewer results in smaller zoom levels, and gradually show more as users zoom-in. Sometimes just a number on even smaller zoom levels.

**Comment by Elfayer** [comment]
Agreed something like this would be perfect for global view:
![2018-06-07 11_25_23-vue-people-2](https://user-images.githubusercontent.com/15869149/41076810-f6f721f6-6a45-11e8-9469-19f53e43ad80.png)

**Comment by lordfuoco** [comment]
We discussed this pretty much immediately while planning vue-people, we just decided to postpone this feature until there was the need! Well apparently it appeared on day two!
We planned to integrate this:
https://github.com/jperelli/vue2-leaflet-markercluster
https://github.com/Leaflet/Leaflet.markercluster

@SevenOutman @Elfayer  what do you think ?

**Comment by Elfayer** [comment]
Sounds great!
I just hope you can still customize to show the faces on the map when you zoom enough.

**Comment by lordfuoco** [comment]
@Elfayer yes it should be possible, will have to investigate this a bit, me or anybody who wants to pick this up. I prioritised small bugs and the hide email feature ( #13 )  at the moment
