### ISSUE TITLE
Better position pin

### ISSUE THREAD

**Issue by Elfayer** [pulilab/vue-people#17]
I feel like I'm in the sea:
![2018-06-07 11_30_03-vue-people](https://user-images.githubusercontent.com/15869149/41076848-3a775ed2-6a46-11e8-868e-40950e6921b9.png)
While I'm not:
![2018-06-07 11_31_53-vue-people](https://user-images.githubusercontent.com/15869149/41076884-6a3f5336-6a46-11e8-92a2-ecf7cbcff65f.png)

The pin **is not** positioned based on the bottom end.

**Comment by lordfuoco** [comment]
Yeah we may need to double check the positioning of the DivMarker
