### ISSUE TITLE
Add library author category

### ISSUE THREAD

**Issue by gustojs** [pulilab/vue-people#30]
Between the `core dev` and `just a dev` groups of Vue users there's also the group of users who write / maintain vue-related libraries. Having a separate group for them would be very nice.

**Comment by lordfuoco** [comment]
@gustojs what colour is usually associated to vue-libraries dev ? And how would you immagine this to work? 
- the user select it itself
- admin enable it
- automatic association from github ?

**Comment by gustojs** [comment]
Not sure if automatic association will properly recognize it f.e. when the library is written under organization but it could be nice.
User selection + enabling by admin (with an issue where you can suggest somebody) can work too. As for colors, no preferences. On Discord we've chosen the colors pretty randomly - just took what's still left.

**Comment by lordfuoco** [comment]
If we don't put any automatic check and we just rely on the honesty of the users we can add the new user-type quite easily 

@paizai we just need a pin icon and a color to define in the code, the rest is configured through admin interface
