### ISSUE TITLE
Legend disappears on some mobile viewports 

### ISSUE THREAD

**Issue by lordfuoco** [pulilab/vue-people#57]

**Comment by TTeRzY** [comment]
.map-legend class has a height of 30px that's why the legend disappears.
You should add 30px height after @media only screen and (min-width: 1000px)

**Comment by lordfuoco** [comment]
@paizai What do you think ?  @TTeRzY Thank you :)

**Comment by lordfuoco** [comment]
@TTeRzY So I discussed this with @paizai he is concerned that the fix you proposed would generate problems with a tablet layout.  
As a workaround we absolutely positioned the legend on mobile and even if we are not 100% happy with it for now will do! 

We are planning a mobile / tablet ui 're-think' soon-ish and this will be addressed better there
